{{/*
Один Secret cloud-credentials, в котором ключ <name>-credentials = INI-формат
с access_key_id и secret_access_key. Это пробрасывается в Velero deployment
и связывается с конкретным BSL через credential.name + credential.key.
*/}}
{{- $backends := dig "s3Backends" list .Values.velero }}
{{- if $backends }}
apiVersion: v1
kind: Secret
metadata:
  name: cloud-credentials
  namespace: d8-velero
  labels:
    {{- include "velero.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $b := $backends }}
  {{ $b.name }}: |
    [default]
    aws_access_key_id={{ $b.accessKey }}
    aws_secret_access_key={{ $b.secretKey }}
  {{- end }}
{{- end }}
{{- $caBackends := list }}
{{- range $b := $backends }}
  {{- if $b.caCert }}
    {{- $caBackends = append $caBackends $b }}
  {{- end }}
{{- end }}
{{- range $b := $caBackends }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ca-bundle-{{ $b.name }}
  namespace: d8-velero
  labels:
    {{- include "velero.labels" . | nindent 4 }}
data:
  ca.crt: |
    {{- $b.caCert | nindent 4 }}
{{- end }}
